Download actions/action_versions latest release on win/linux/mac and set ACTIONS_RUNNER_ACTION_ARCHIVE_CACHE.
TingluoHuang/runner-images pull request #1
Opened 2023-09-24 02:33 UTC by TingluoHuang

# Description
New tool, Bug fixing, or Improvement?
Please include a summary of the change and which issue is fixed. Also include relevant motivation and context.
**For new tools, please provide total size and installation time.**

#### Related issue:

## Check list
- [ ] Related issue / work item is attached
- [ ] Tests are written (if applicable)
- [ ] Documentation is updated (if applicable)
- [ ] Changes are tested and related VM images are successfully generated

2023-09-28 15:09 UTC, mikhailkoliada requested changes

2023-09-28 15:09 UTC, mikhailkoliada commented on images/linux/scripts/installers/action-archive-cache.sh
> +latestReleaseName=$(curl -s -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/actions/action-versions/releases/latest | jq --raw-output  '.na
I'd use the `get_github_package_download_url` helper which we have differed in the runner-images repo here: https://github.com/actions/runner-images/blob/a4234d46c7b5db3e2187af0db44790e1a898c802/images/linux/scripts/helpers/install.sh#L69C1-L69C33

2023-09-28 15:09 UTC, mikhailkoliada commented on images/linux/scripts/installers/action-archive-cache.sh
> +echo "ACTIONS_RUNNER_ACTION_ARCHIVE_CACHE=$ACTION_ARCHIVE_CACHE_DIR" | tee -a /etc/environment
you can use the `addEtcEnvironmentVariable` helper defined here https://github.com/actions/runner-images/blob/main/images/linux/scripts/helpers/etc-environment.sh

2023-09-28 15:09 UTC, mikhailkoliada commented on images/linux/scripts/installers/action-archive-cache.sh
> +curl -s -O -L https://github.com/actions/action-versions/releases/download/$latestReleaseName/action-versions.tar.gz
downloading once may fail, I'd use the `download_with_retries` helper defined here:  https://github.com/actions/runner-images/blob/main/images/linux/scripts/helpers/install.sh

2023-09-28 15:09 UTC, mikhailkoliada commented on images/linux/scripts/installers/action-archive-cache.sh
> +tar xzf ./action-versions.tar.gz
use `-C` tar option to specify the extraction directory, so you can drop `pushd` and `popd`calls

2023-09-28 15:09 UTC, mikhailkoliada commented on images/linux/scripts/installers/action-archive-cache.sh
> +rm ./action-versions.tar.gz
`download_with_retries` downloads to /tmp so once helper is used you can drop the explicit removal

2023-09-28 15:09 UTC, mikhailkoliada commented on images/linux/scripts/installers/action-archive-cache.sh
> +ls -l ./
We probably do not need to ls it

2023-09-28 15:09 UTC, mikhailkoliada commented on images/macos/provision/core/action-archive-cache.sh
> +
for macOS helpers are doubled, so you can use literally the same approach as I described for linux above :)

2023-09-28 15:27 UTC, mikhailkoliada requested changes

2023-09-28 15:27 UTC, mikhailkoliada commented on images/win/scripts/Installers/Install-ActionArchiveCache.ps1
> +$latestRelease = Invoke-RestMethod -Uri "https://api.github.com/repos/actions/action-versions/releases/latest"
use `Start-DownloadWithRetry` which is defined here https://github.com/actions/runner-images/blob/a4234d46c7b5db3e2187af0db44790e1a898c802/images/macos/helpers/Common.Helpers.psm1#L123

2023-09-28 15:27 UTC, mikhailkoliada commented on images/win/scripts/Installers/Install-ActionArchiveCache.ps1
> +Remove-Item $actionVersionsArchivePath -Force
once Start-DownloadWithRetry is enacted you do not need the line to remove the archive

2023-09-28 15:27 UTC, mikhailkoliada commented on images/win/scripts/Installers/Install-ActionArchiveCache.ps1
> +[string]$downloadUrl = $latestRelease.assets.browser_download_url -match "action-versions.zip"
I guess you can try to utilise the `Get-GitHubPackageDownloadUrl` helper here

2023-10-01 20:19 UTC, closed without merging

2023-10-01 20:19 UTC, TingluoHuang commented
Close since PR has created against upstream